version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/django
      # - /home/braham/INTEGRACION/WEBPY/sql/data.sql:/docker-entrypoint-initdb.d/inserts.sql
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
  db:
    image: postgres
    ports: ["5432:5432"]
    volumes:
       - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
    
  # :
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - "73:80"
  #   depends_on:
  #     - dbpgadmin

    